[project]
name = "rvcomp-doc"
version = "1.0.0"
description = "RVcomp Documentation"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "sphinx-rtd-theme>=3.0.2",
    "sphinx>=8.1.3",
    "myst-parser>=4.0.1",
]
